# docker-compose.override.yml
version: "3.8"

services:
  frontend:
    container_name: gespack_frontend
    build:
      context: .
      dockerfile: dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
