version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: GesPack-DB
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shared-network

volumes:
  postgres_data:
    driver: local

networks:
  shared-network:
    external: true
